sudo: required
language: python 
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
os:
  - linux
python:
  - "3.6"
install: 
  - pip install -r requirements.txt  
script: 
  - sudo /bin/bash k8s-images.sh
  - sudo /bin/bash network-images.sh
  - sudo rm -f /home/travis/.docker/config.json