sudo: required
language: python 
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
python:
  - "3.6"
os:
  - linux
script: 
  -  /bin/bash set_travis_env.sh
  -  /bin/bash sync_image.sh