sudo: required
language: python 
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
python:
  - "3.6"
os:
  - linux

install: 
  - pip install -r requirements.txt  
script: 
  -  /bin/bash k8s-images.sh
  -  /bin/bash network-images.sh
  - rm -f /home/travis/.docker/config.json