sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
os:
  - linux
script: 
  - sudo /bin/bash k8s-images.sh
  - sudo /bin/bash network-images.sh
  - sudo rm -f /home/travis/.docker/config.json